### ISSUE TITLE
Purpose of template.shape[::-1]

### ISSUE THREAD

**Issue by BenRoe** [drov0/python-imagesearch#13]
Hello,
i am learning Python and try to understand your code.
Can you explain the purpose of the following code? 

https://github.com/drov0/python-imagesearch/blob/88bf9eecb772ff5e657d4780d65cdff87cc5527d/imagesearch.py#L121

Many thanks for the great Post about "How I made a python bot to automate a tactical mmorpg".

**Comment by drov0** [comment]
Heya, thanks for your comment :) 

it's been a while since I wrote that bit so I am not 100% sure, but this part of the code basically inverts the array. (if the array is [1234], [::-1] will result in [4321] )I think I do that because the image gets upside down (or left and right are inverted) during `cv2.imread`, so it messes up the coordinates for matchTemplate

**Comment by RomanJos** [comment]
I had an issue where template was nonetype because I specified the wrong file and thankfully I found this issue even thought its unrelated, I guess we can put an exception or something here
