### ISSUE TITLE
Can imagesearch handle an image on a different background?

### ISSUE THREAD

**Issue by pa345** [drov0/python-imagesearch#54]
I want to search for an image that could appear on different backgrounds in a game, however imagesearch does not appear to be able to do this. My screenshot plus 3 examples of the image I am looking for are given here,

https://imgur.com/a/pUNVKET

In the last image, I removed the background to isolate the feature I want. Here is my script:

```
#!/usr/bin/python3

from python_imagesearch.imagesearch import imagesearch_loop

pos = imagesearch_loop("./exchange_sand.png", 0.2, 0.8)
print("position : ", pos[0], pos[1])
```
When I use the exact file (exchange_sand.png) it works fine. But either of the other 2 images (exchange_forest.png and exchange_transp.png) it fails to find the image. I have tried adjusting the threshold from 0.8 downward but it does not work either.

Any ideas?

**Comment by drov0** [comment]
Hey, transparent images do not work, so the isolated one is not gonna work. As for the forest one, it's also not gonna work because it's not going to find all the extra details (forest etc) leading to a non-match. Basically you have to understand that it's going to look for an almost exact match for the file you provided, including all the details like the trees etc.

I suggest taking a smaller screenshot of a part of the building that is common in both envs like this 
![image](https://github.com/drov0/python-imagesearch/assets/22356916/63663ab8-fd3e-4520-a7c1-d8628a3b71b9)

That way the whole image can be found regardless if it's in a forest or in a sand environment.
